name: Temporal

on:
  workflow_dispatch:  # Esto permite iniciar el flujo de trabajo manualmente
  push:
   paths:
     - 'temp/*1.json'

jobs:
  procesar-jsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Esperar 5 seg
        run: sleep 5

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar temp_js.js
        run: node assets/js/temp_js.js

      - name: Commit de resultados en _data
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add _data/
          git rm temp/*.json || true
          git commit -m "Procesados de /temp" || echo "Nada para commitear"
          git push
